/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemperhotelan.View;
import sistemperhotelan.model.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author bijak
 */
public class Dashboard extends javax.swing.JFrame {
    static final String DB_URL = "jdbc:mysql://localhost/tubespbo";
    static final String DB_USER = "root";
    static final String DB_PASS = "";
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    List<Kamar> listKamar = new ArrayList<>();
    Karyawan worker;
    /**
     * Creates new form UI
     */
    public Dashboard() {
        initComponents();
        this.InitKamar();
    }
    
    public void InitKamar(){
        try {
            conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);
            stmt = conn.createStatement();
            String sql = "SELECT * FROM kamar";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                listKamar.add(new Kamar(rs.getString("tipe"), rs.getInt("nomor"),rs.getString("lantai"),rs.getString("status")));
            }

            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.setList();
    }
    
    public void setList(){
        DefaultListModel p1 = new DefaultListModel();
        DefaultListModel p2 = new DefaultListModel();
        DefaultListModel p3 = new DefaultListModel();
        for (int i = 0; i < listKamar.size(); i++) {
//            System.out.print(listKamar.get(i).getTipe().equals("Standar"));
            if ( listKamar.get(i).getTipe().equals("Standar") && listKamar.get(i).getStatus().equals("Kosong") ){
                p1.addElement(listKamar.get(i).getLantai()+"- No"+listKamar.get(i).getNomor());
            } else if ( listKamar.get(i).getTipe().equals("Superior") && listKamar.get(i).getStatus().equals("Kosong") ){
                p2.addElement(listKamar.get(i).getLantai()+"- No"+listKamar.get(i).getNomor());
            } else {
                p3.addElement(listKamar.get(i).getLantai()+"- No"+listKamar.get(i).getNomor());
            }
        }
        this.ListStandar.setModel(p1);
        this.ListSuperior.setModel(p2);
        this.ListDeluxe.setModel(p3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TabDaftarKamar = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Tipe01 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListStandar = new javax.swing.JList<>();
        Tipe02 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListSuperior = new javax.swing.JList<>();
        Tipe03 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListDeluxe = new javax.swing.JList<>();
        TabBooking = new javax.swing.JPanel();
        HaloAdmin1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListStandar.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListStandar);

        javax.swing.GroupLayout Tipe01Layout = new javax.swing.GroupLayout(Tipe01);
        Tipe01.setLayout(Tipe01Layout);
        Tipe01Layout.setHorizontalGroup(
            Tipe01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tipe01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        Tipe01Layout.setVerticalGroup(
            Tipe01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tipe01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Standar", Tipe01);

        ListSuperior.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListSuperior);

        javax.swing.GroupLayout Tipe02Layout = new javax.swing.GroupLayout(Tipe02);
        Tipe02.setLayout(Tipe02Layout);
        Tipe02Layout.setHorizontalGroup(
            Tipe02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tipe02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        Tipe02Layout.setVerticalGroup(
            Tipe02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tipe02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Superior", Tipe02);

        ListDeluxe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ListDeluxe);

        javax.swing.GroupLayout Tipe03Layout = new javax.swing.GroupLayout(Tipe03);
        Tipe03.setLayout(Tipe03Layout);
        Tipe03Layout.setHorizontalGroup(
            Tipe03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tipe03Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        Tipe03Layout.setVerticalGroup(
            Tipe03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tipe03Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Deluxe", Tipe03);

        javax.swing.GroupLayout TabDaftarKamarLayout = new javax.swing.GroupLayout(TabDaftarKamar);
        TabDaftarKamar.setLayout(TabDaftarKamarLayout);
        TabDaftarKamarLayout.setHorizontalGroup(
            TabDaftarKamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabDaftarKamarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        TabDaftarKamarLayout.setVerticalGroup(
            TabDaftarKamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabDaftarKamarLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Daftar Kamar", TabDaftarKamar);

        javax.swing.GroupLayout TabBookingLayout = new javax.swing.GroupLayout(TabBooking);
        TabBooking.setLayout(TabBookingLayout);
        TabBookingLayout.setHorizontalGroup(
            TabBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        TabBookingLayout.setVerticalGroup(
            TabBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Booking Saat Ini", TabBooking);

        HaloAdmin1.setText("<html><h3>Halo, </h3></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HaloAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HaloAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel HaloAdmin1;
    private javax.swing.JList<String> ListDeluxe;
    private javax.swing.JList<String> ListStandar;
    private javax.swing.JList<String> ListSuperior;
    private javax.swing.JPanel TabBooking;
    private javax.swing.JPanel TabDaftarKamar;
    private javax.swing.JPanel Tipe01;
    private javax.swing.JPanel Tipe02;
    private javax.swing.JPanel Tipe03;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
